# IW 1
# motor_offsets: 
#   theta1: 142.0
#   theta2: 105.0
#   theta3: 26.0
#   theta4: 130.0
#   theta5: 150.0

# motor_bounds:
#   joint1_outer_bound: 
#   joint1_inner_bound:
#   joint2_outer_bound: 70.0 
#   joint2_inner_bound: 245.0 
#   joint3_outer_bound: -5.0
#   joint3_inner_bound: 175.0 
#   joint4_outer_bound: 168.0 
#   joint4_inner_bound: -7.0 
#   joint5_outer_bound: 
#   joint5_inner_bound:

# IW 2
motor_offsets: 
  theta1: 60.44
  theta2: 105.6
  theta3: 37.0
  theta4: 211.4
  theta5: 116.0

motor_bounds:
  joint1_outer_bound: 
  joint1_inner_bound:
  joint2_outer_bound: 65.0
  joint2_inner_bound: 250.0 
  joint3_outer_bound: 5.0
  joint3_inner_bound: 180.0
  joint4_outer_bound: 240.0
  joint4_inner_bound: 75.0
  joint5_outer_bound: 
  joint5_inner_bound: